HelloWorld/Models/Person.cs
using FluentValidation.Attributes;
using HelloWorld.Models.Validators;

namespace HelloWorld.Models
{
    [Validator(typeof(PersonValidator))]
    public class Person
    {
        public int PersonID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Opinion { get; set; }
        public string Genre { get; set; }
        public int Age { get; set; }
    }
}

HelloWorld/Models/Validators/PersonValidator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FluentValidation;

namespace HelloWorld.Models.Validators
{
    public class PersonValidator : AbstractValidator<Person>
    {
        public PersonValidator()
        {
           // RuleFor(x => x.Name).NotEmpty().WithMessage("The field name not should be empty.");
        }
    }
}

HelloWorld/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelloWorld.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HelloWorld/Controllers/PersonController.cs
using HelloWorld.Interfaces;
using HelloWorld.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace HelloWorld.Controllers
{
    public class PersonController : Controller
    {
        private readonly IPerson repository;
        public PersonController(IPerson _repository)
        {
            repository = _repository;
        }


        // GET: Person
        public async Task<ActionResult> Index(string message = "")
        {
            ViewBag.message = message;
            var personList = await repository.GetPersonList();
            return View(personList);
        }

        [HttpGet]
        public async Task<JsonResult> GetPersons()
        {
            var personList = await repository.GetPersonList();
            return Json(personList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> SavePerson(Person person)
        {
            var result = await repository.AddPerson(person);
            if (result == "success")
                return Json(result, JsonRequestBehavior.AllowGet);
            return Json("error", JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Details(int personID, string type = "details")
        {
            var person = await repository.GetPerson(personID);
            if (type == "delete")
                ViewBag.isDelete = true;
            ViewBag.personId = personID;
            return View(person);
        }

        public async Task<ActionResult> Delete(int personID)
        {
            var result = await repository.DeletePerson(personID);
            return RedirectToAction("Index", new { message = "The register was deleted success!" });
        }
    }
}

HelloWorld/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HelloWorld/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HelloWorld/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<button id="new-register" class="btn btn-secondary">New register</button>
<div id="persons" class="mt-2">
    <table class="table table-hover table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Last name</th>
                <th>Age</th>
                <th>Opinion</th>
                <th>Genre</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="person in persons">
                <td>{{person.Name}}</td>
                <td>{{person.LastName}}</td>
                <td class="text-center"><span class="badge badge-info">{{person.Age}}</span></td>
                <td>{{person.Opinion}}</td>
                <td>{{person.Genre}}</td>
                <td class="text-center">
                    <a href="#" class="btn btn-success btn-sm"><i class="fa fa-edit" aria-hidden="true"></i></a>
                    <a href="#" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        </tbody>

    </table>
</div>
<div class="modal fade" id="modal-new-register" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div id="form">
                <form v-on:submit.prevent="$validator.validateAll();onSubmit()">
                    <div class="modal-header">
                        <h5 class="modal-title">New person</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group" v-bind:class="{'has-danger': errors.has('name')}">
                            <label class="fom-control-label">Name</label>
                            <div class="control">
                                <input name="name" v-model="form.name" v-validate="'required|min:3'" class="form-control" v-bind:class="{'form-control-danger': errors.has('name')}" type="text" placeholder="Name">
                            </div>
                            <div class="form-control-feedback" v-show="errors.has('name')">
                                {{ errors.first('name') }}
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">Lastname</label>
                            <div class="control">
                                <input name="lastName" v-model="form.lastName" v-validate="'required'" v-bind:class="{'is-danger': errors.has('lastName')}" class="form-control" type="text" placeholder="Lastname">
                            </div>
                            <p class="help is-danger" v-show="errors.has('lastName')">
                                {{ errors.first('lastName') }}
                            </p>
                        </div>

                        <div class="field">
                            <label class="label">Age</label>
                            <div class="control">
                                <div class="select">
                                    <input name="name" v-model="form.age" v-bind:class="{'is-danger': errors.has('name')}" class="form-control" type="number" placeholder="Age">
                                </div>
                                <p class="help is-danger" v-show="errors.has('lastName')">
                                    {{ errors.first('age') }}
                                </p>
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">Opinion</label>
                            <div class="control">
                                <textarea v-model="form.opinion" v-bind:class="{'is-danger': errors.has('name')}" class="form-control" placeholder="Opinion"></textarea>
                            </div>
                            <p class="help is-danger" v-show="errors.has('lastName')">
                                {{ errors.first('opinion') }}
                            </p>
                        </div>

                        <div class="form-group">
                            <label class="label">Genre</label>
                            <select v-model="form.genre" class="form-control">
                                <option value="Female">Female</option>
                                <option value="Male">Male</option>
                            </select>
                            <p class="help is-danger" v-show="errors.has('lastName')">
                                {{ errors.first('genre') }}
                            </p>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="submit" v-bind:disabled="errors.any()" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i>Save changes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
                {{message}}
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="@Url.Content("~/Scripts/vuejs/home.js")"></script>
}

HelloWorld/Views/Person/Details.cshtml
@model HelloWorld.Models.Person
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<ul class="list-group">
    <li class="list-group-item">Name: @Model.Name @Model.LastName</li>
    <li class="list-group-item">Genre: @Model.Genre</li>
    <li class="list-group-item">Age: <span class="badge badge-info">@Model.Age</span></li>
    <li class="list-group-item">Opinion: @Model.Opinion</li>
</ul>


<a href="#">Back to list</a> |
@if (ViewBag.isDelete)
{
    @Html.ActionLink(
    "Delete",
    "Delete",
    new { personID = ViewBag.personId },
    new { onclick = "return confirm('Are you sure you wish to delete this article?');" });
}

HelloWorld/Views/Person/Index.cshtml
@model IQueryable<HelloWorld.Models.Person>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Persons</h2>
<a class="btn btn-outline-primary" href="#">New person</a>
<table class="table table-striped table-bordered table-hover mt-3">
    <thead class="thead-dark">
        <tr>
            <th>Name</th>
            <th>Last name</th>
            <th>Age</th>
            <th>Opinion</th>
            <th>Genre</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.LastName</td>
                <td><span class="badge badge-secondary">@item.Age</span></td>
                <td>@item.Opinion</td>
                <td>@item.Genre</td>
                <td>
                    <a href="@Url.Action("Details","Person",new { personID=item.PersonID})" class="edit">Edit</a>
                    <a href="@Url.Action("Details","Person",new { personID=item.PersonID, type="delete"})" class="delete">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@if (ViewBag.message != "")
{
    <div class="alert alert-info">
        <p> @ViewBag.message</p>
    </div>
}

HelloWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/font")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        html, body {
            font-family: Poppins !important;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Sign out</a>
            </li>
        </ul>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                <span data-feather="home"></span>
                                Dashboard <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file"></span>
                                Orders
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="shopping-cart"></span>
                                Products
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="users"></span>
                                Customers
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bar-chart-2"></span>
                                Reports
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="layers"></span>
                                Integrations
                            </a>
                        </li>
                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Saved reports</span>
                        <a class="d-flex align-items-center text-muted" href="#">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Current month
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Last quarter
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Social engagement
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Year-end sale
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                @RenderBody()
            </main>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/vue")
    <script src="@Url.Content("https://unpkg.com/vee-validate@2.0.0-rc.18/dist/vee-validate.js")"></script>
    @RenderSection("scripts", required: false)
</body>
</html>